-- Baseline schema for spring-react-boilerplate (PostgreSQL 17).
-- Auto-generated from the JPA entities: Hibernate created the schema, captured via pg_dump.
-- Do NOT edit by hand. Subsequent changes go in new V2__*.sql, V3__*.sql migrations.


CREATE TABLE public.examples (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(150) NOT NULL,
    description character varying(500),
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE public.examples ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.examples_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.feature_flags (
    enabled boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id character(36) NOT NULL,
    workspace_id character(36) NOT NULL,
    flag_key character varying(60) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255)
);

CREATE TABLE public.files (
    created_at timestamp(6) without time zone,
    size bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    extension character varying(20),
    storage_type character varying(20) NOT NULL,
    id character(36) NOT NULL,
    content_type character varying(255) NOT NULL,
    created_by character varying(255),
    original_filename character varying(255) NOT NULL,
    storage_key character varying(255) NOT NULL,
    thumbnail_key character varying(255),
    updated_by character varying(255),
    CONSTRAINT files_storage_type_check CHECK (((storage_type)::text = ANY ((ARRAY['FILESYSTEM'::character varying, 'S3'::character varying, 'R2'::character varying])::text[])))
);

CREATE TABLE public.news (
    featured boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    featured_image_id character(36),
    id character(36) NOT NULL,
    workspace_id character(36) NOT NULL,
    title character varying(300) NOT NULL,
    slug character varying(320) NOT NULL,
    content text,
    created_by character varying(255),
    updated_by character varying(255)
);

CREATE TABLE public.news_attachment_ids (
    sort_order integer NOT NULL,
    attachment_id character(36) NOT NULL,
    news_id character(36) NOT NULL,
    CONSTRAINT news_attachment_ids_sort_order_check CHECK ((sort_order >= 0))
);

CREATE TABLE public.news_image_ids (
    sort_order integer NOT NULL,
    image_id character(36) NOT NULL,
    news_id character(36) NOT NULL,
    CONSTRAINT news_image_ids_sort_order_check CHECK ((sort_order >= 0))
);

CREATE TABLE public.news_tags (
    news_id character(36) NOT NULL,
    tag character varying(50) NOT NULL
);

CREATE TABLE public.notifications (
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone,
    read_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id character(36) NOT NULL,
    recipient_id character(36) NOT NULL,
    workspace_id character(36) NOT NULL,
    type character varying(60) NOT NULL,
    title character varying(200) NOT NULL,
    created_by character varying(255),
    message text,
    updated_by character varying(255)
);

CREATE TABLE public.organizations (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id character(36) NOT NULL,
    logo_id character(36),
    phone_number character varying(50),
    slug character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    address character varying(500),
    description character varying(1000),
    created_by character varying(255),
    updated_by character varying(255)
);

CREATE TABLE public.otps (
    used boolean NOT NULL,
    code character varying(8) NOT NULL,
    created_at timestamp(6) without time zone,
    expiry_time timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    sending_channel character varying(10) NOT NULL,
    type character varying(40) NOT NULL,
    created_by character varying(255),
    destination character varying(255) NOT NULL,
    updated_by character varying(255),
    CONSTRAINT otps_sending_channel_check CHECK (((sending_channel)::text = ANY ((ARRAY['SMS'::character varying, 'EMAIL'::character varying])::text[]))),
    CONSTRAINT otps_type_check CHECK (((type)::text = ANY ((ARRAY['ACCOUNT_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying, 'CHANGE_PASSWORD'::character varying, 'LOGIN_2FA'::character varying])::text[])))
);

ALTER TABLE public.otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.refresh_tokens (
    revoked boolean NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id character(36) NOT NULL,
    token character varying(64) NOT NULL,
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.roles (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(50) NOT NULL,
    display_name character varying(100),
    created_by character varying(255),
    description character varying(255),
    updated_by character varying(255)
);

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.shedlock (
    lock_until timestamp(6) with time zone NOT NULL,
    locked_at timestamp(6) with time zone NOT NULL,
    name character varying(64) NOT NULL,
    locked_by character varying(255) NOT NULL
);

CREATE TABLE public.user_roles (
    role_id bigint NOT NULL,
    user_id character(36) NOT NULL
);

CREATE TABLE public.users (
    activated boolean,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id character(36) NOT NULL,
    organization_id character(36),
    profile_image_id character(36),
    workspace_id character(36),
    created_by character varying(255),
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    phone_number character varying(255),
    surname character varying(255),
    updated_by character varying(255)
);

CREATE TABLE public.workspaces (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    brand_color character varying(20),
    id character(36) NOT NULL,
    logo_id character(36),
    organization_id character(36) NOT NULL,
    phone_number character varying(50),
    slug character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    address character varying(500),
    description character varying(1000),
    created_by character varying(255),
    updated_by character varying(255)
);

ALTER TABLE ONLY public.examples
    ADD CONSTRAINT examples_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.files
    ADD CONSTRAINT idx_files_storage_key UNIQUE (storage_key);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT idx_refresh_tokens_token UNIQUE (token);

ALTER TABLE ONLY public.news_attachment_ids
    ADD CONSTRAINT news_attachment_ids_pkey PRIMARY KEY (sort_order, news_id);

ALTER TABLE ONLY public.news_image_ids
    ADD CONSTRAINT news_image_ids_pkey PRIMARY KEY (sort_order, news_id);

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.news_tags
    ADD CONSTRAINT news_tags_pkey PRIMARY KEY (news_id, tag);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT otps_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shedlock
    ADD CONSTRAINT shedlock_pkey PRIMARY KEY (name);

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT uk_feature_flag_workspace_key UNIQUE (workspace_id, flag_key);

ALTER TABLE ONLY public.news
    ADD CONSTRAINT uk_news_workspace_slug UNIQUE (workspace_id, slug);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT uk_organizations_slug UNIQUE (slug);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk_roles_name UNIQUE (name);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT uk_workspaces_slug UNIQUE (slug);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);

CREATE INDEX idx_feature_flag_workspace ON public.feature_flags USING btree (workspace_id);

CREATE INDEX idx_news_attachment_ids_news ON public.news_attachment_ids USING btree (news_id);

CREATE INDEX idx_news_created_at ON public.news USING btree (created_at);

CREATE INDEX idx_news_featured ON public.news USING btree (featured);

CREATE INDEX idx_news_image_ids_news ON public.news_image_ids USING btree (news_id);

CREATE INDEX idx_news_tags_news ON public.news_tags USING btree (news_id);

CREATE INDEX idx_news_workspace ON public.news USING btree (workspace_id);

CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at);

CREATE INDEX idx_notifications_read ON public.notifications USING btree (is_read);

CREATE INDEX idx_notifications_recipient ON public.notifications USING btree (workspace_id, recipient_id);

CREATE INDEX idx_organizations_created_at ON public.organizations USING btree (created_at);

CREATE INDEX idx_otps_destination_type ON public.otps USING btree (destination, type);

CREATE INDEX idx_otps_expiry_time ON public.otps USING btree (expiry_time);

CREATE INDEX idx_refresh_tokens_expires_at ON public.refresh_tokens USING btree (expires_at);

CREATE INDEX idx_refresh_tokens_user ON public.refresh_tokens USING btree (user_id);

CREATE INDEX idx_user_roles_role ON public.user_roles USING btree (role_id);

CREATE INDEX idx_users_created_at ON public.users USING btree (created_at);

CREATE INDEX idx_workspaces_created_at ON public.workspaces USING btree (created_at);

CREATE INDEX idx_workspaces_organization ON public.workspaces USING btree (organization_id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.news_attachment_ids
    ADD CONSTRAINT fk97g74u1s3jb9qvq304gs068dc FOREIGN KEY (news_id) REFERENCES public.news(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.news_tags
    ADD CONSTRAINT fki06sdgpsvq2oxtharq5q1rc3x FOREIGN KEY (news_id) REFERENCES public.news(id);

ALTER TABLE ONLY public.news_image_ids
    ADD CONSTRAINT fktjcl0rj1iif8p46pnibv1unjs FOREIGN KEY (news_id) REFERENCES public.news(id);

